### ISSUE TITLE
Remove the gray background color from tile 

### ISSUE THREAD

**Issue by MortezaT** [benhowell/react-grid-gallery#161]
### Expected behavior
[Tile](https://github.com/benhowell/react-grid-gallery/blob/03b1174052851db1fe918f06092b64e968b990bc/src/Image.js#L185) should have transparent background

### Actual behavior
Tile comes with a gray (eee) background that is visible if there is and image with transparent background

### Steps to reproduce behavior
create a gallery with an image that comes with transparent background

**Comment by itoldya** [comment]
Hello @MortezaT! Thanks for your contribution!

Seems that gray background is really a problem for transparent images. 
But I’m not sure that it’s a good idea to change the background color globally for all react-grid-gallery users, since a lot of users already rely on the current color.

I suggest to workaround the problem by overriding CSS rules. 
Define important style rule in your CSS file
```css
.ReactGridGallery_tile{
  background: transparent !important;
}
```

or if you are using CSS Modules you need to define styles in `:global` scope

```css
 :global {
  .ReactGridGallery_tile {
    background: transparent !important;
  }
}
```

**Comment by MortezaT** [comment]
Hi @itoldya 
Thanks for the response.
Since I don't like using `!important` (the quick fix I already applied to my code base 😛 ) I suggest to add a property for controlling bg color. it can be either a simple flag like `isTransparent` to remove the background or `bgColor` which accepts different values.

**Comment by marekves** [comment]
I would also like to easily change the background color when the image is selected? Is there a possibility to do that currently? Thank you in advance :).

**Comment by itoldya** [comment]
@marekves did you try this?
```css
.ReactGridGallery_tile{
  background: transparent !important;
}
```
