### ISSUE TITLE
Want to add custom border to image item in gallery.

### ISSUE THREAD

**Issue by SymntxHomendra51** [benhowell/react-grid-gallery#258]
How to add border to each item in gallery?
or box shadow

**Comment by itoldya** [comment]
Hi! Try to style with CSS. Available class names are `ReactGridGallery_tile`, `ReactGridGallery_tile-viewport`, and `ReactGridGallery_tile-overlay`.

```css
.ReactGridGallery_tile-viewport {
    border: 1px solid black;
}
```
